Repository chili-publish/publisher-interface, pull requests merged in 2022-10, with the labels that each got.

#13 [FEATURE] Tests
  package-lock.json
  package.json
  test/PublisherInterface.spec.ts
  test/README.md
  test/index.html
  test/run_tests.js
  test/testServer.js
  test/tests/addListener.js
  test/tests/executeFunction.js
  test/tests/getPageSnapshot.js
  test/tests/setPropertyGetObject.js
  test/tests/setVariableIsLocked.js
Labels: enhancement, ready to merge

#18 Documentation/update documentation
  README.md
Labels: documentation, ready for review, ready to merge

#16 [FEATURE] Feature/backwards compatible auto add listener
  src/PublisherInterface.ts
  test/tests/registerEventsOnBuild.js
Labels: enhancement, ready for review, ready to merge

#15 [FEATURE] Add compatibility with OnEditorEvent
  src/PublisherInterface.ts
  test/tests/OnEditorEvent.js
  test/tests/registerEventsOnBuild.js
Labels: enhancement, ready for review, ready to merge

#17 [FEATURE] Add alias for editorObject
  src/PublisherInterface.ts
  test/tests/AddListener.js
  test/tests/ExecuteFunction.js
Labels: enhancement, ready for review, ready to merge

#19 Update library version
  package.json
Labels: ready to merge

#22 Wiki
  src/Do I Need To Convert My Integration.md
  src/Why I Cannot Use editorObject.md
Labels: ready for review, ready to merge
