Repository chili-publish/publisher-interface, pull requests merged in 2022-05, with the labels that each got.

#2 [Feature] Add missing OSS documents
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  CODE_OF_CONDUCT.md
  COMMUNICATION_GUIDELINES.md
  CONTRIBUTING.md
Labels: documentation

#3 [Fix] Bump version to 0.1.1
  package.json
Labels: bug

#5 Feature/break up distlib
  .gitignore
  package.json
Labels: enhancement, ready for review

#4 [Feature] Add InternalServerWrapper to dist
  .gitignore
  package-lock.json
  package.json
Labels: enhancement, open for discussion, ready for review
