Repository chili-publish/publisher-interface, pull requests merged in 2022-11, with the labels that each got.

#24 [Bug #23] webpack4 compatibility
  .parcelrc
  package-lock.json
  package.json
Labels: bug, ready for review, ready to merge

#25 [BUG] Fix events expecting a string instead of a string[]
  package.json
  src/PublisherInterface.ts
Labels: bug, ready for review, ready to merge

#28 Typo
  src/Differences With editorObject.md
Labels: documentation

#31 [Fix] Replace interface with publisher due to TypeScript incompatibilities
  src/Differences With editorObject.md
  src/Home.md
  src/Moving to Publisher Interface.md
Labels: documentation, ready to merge

#32 Update README from wiki for interface to publisher
  README.md
  package.json
Labels: documentation, ready to merge
